name = "HarfBuzz"
uuid = "9e8b9c2b-5c3e-4e6f-b1a4-2c0f6b4f3e2a"
authors = ["Sebastien Celles <s.celles@gmail.com>"]
version = "0.1.0"

[deps]
HarfBuzz_jll = "2e76f6c2-a576-52d4-95c1-20adfe4de566"

[weakdeps]
FreeType = "b38be410-82b0-50bf-ab77-7b57e271db43"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"

[extensions]
HarfBuzzFreeTypeAbstractionExt = ["FreeTypeAbstraction", "FreeType"]
HarfBuzzFreeTypeExt = "FreeType"

[compat]
Aqua = "0.8"
FreeType = "4"
FreeTypeAbstraction = "0.10"
HarfBuzz_jll = "100.14002"
Test = "1"
TestItemRunner = "1"
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
FreeType = "b38be410-82b0-50bf-ab77-7b57e271db43"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "FreeType", "FreeTypeAbstraction", "Test", "TestItemRunner"]
